// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateTodoInput struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUpInput struct {
	Name     string `json:"name"`
	Surname  string `json:"surname"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
